version: '3.8'

services:
  web:
    build:
      context: ./django_app
      dockerfile: ../docker/web/Dockerfile
    image: django-app:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./django_app:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    image: postgres-app:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local